[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedByDefault = false
  [docker.tls]
    cert = "/etc/traefik/certs/local-cert.pem"
    key = "/etc/traefik/certs/local-key.pem"

[api]
  insecure = true
  dashboard = true
  debug = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.web-secure]
    address = ":443"

[providers]
  [providers.file]
    filename = "/etc/traefik/traefik.config.toml"
    watch = true